#!/bin/python3
from flask import Flask, request

app = Flask(__name__)

@app.route('/server', methods=['POST'])
def handle_webhook():
   if request.method == 'POST':
       data = request.data
       print("Received data:", data.decode("utf-8"))

       with open('received_data.txt', 'w') as file:
           file.write(data.decode("utf8"))
       
       return "Webhook data received", 200
   else:
       return "Unsupported method", 501

if __name__ == '__main__':
   app.run(host='192.168.66.2', port=80) # Attacker address
   
